version: '3.7'
services: 
  nuxt:
    container_name: DEV_${APP_NAME}
    build: 
      context: .
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - ${APP_PORT}:3000
    working_dir: /usr/src/app/${APP_NAME}
    volumes:
      - ./${APP_NAME}:/usr/src/app/${APP_NAME}
    environment: 
      - HOST=0.0.0.0
    tty: true